# Generated by Django on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gymapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
