# Generated by Django 6.0.4 on 2026-05-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gymapp", "0002_equipment_price_equipment_purchase_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipplan",
            name="fee",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
