# Generated by Django 6.0.4 on 2026-05-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gymapp", "0003_alter_membershipplan_fee"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="subject",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
